INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'index_title', 'Your first x0-app!');
INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'debug_level', '0');
INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'display_language', 'en');
INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'default_screen', 'WelcomeScreen');
INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'parent_window_url', '""');
INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'subdir', '/static');
INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'preload_script', '');
INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'config_file_menu', 'menu.json');
INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'config_file_object', 'object.json');
INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'config_file_skeleton', 'skeleton.json');
INSERT INTO system.config (app_id, config_group, "value") VALUES ('x0-skeleton', 'preload_script', 'undefined');
